////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  Copyright (C) 2016-2026, goatpig.                                         //
//  Distributed under the MIT license                                         //
//  See LICENSE-MIT or https://opensource.org/licenses/MIT                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <cstring>
#include <unordered_map>
#include <arpa/inet.h>

#include "BlockchainScanner.h"
#include <Utils/log.h>
#include <Utils/BtcUtils.h>
#include <Utils/varint.h>
#include <Utils/TxOutScrRef.h>
#include <Utils/DBUtils.h>
#include <Utils/BCTX.h>
#include <Utils/ArmoryConfig.h>
#include <Utils/UniversalTimer.h>
#include <TxClasses.h>

#include "BlockDataMap.h"
#include "TxHashFilters.h"
#include "txio.h"
#include "StoredBlockObj.h"
#include "lmdb_wrapper.h"
#include "Blockchain.h"
#include "ScrAddrFilter.h"

using namespace Armory;

////////////////////////////////////////////////////////////////////////////////
// ScannerContext
void ScannerContext::init(LMDBBlockDatabase* db)
{
   if (!hashMap_.empty()) {
      throw std::runtime_error("hashmap isn't empty");
   }
   auto tx = db->beginTransaction(
      DB_SELECT::KNOWNHASHES, LMDB::Mode::ReadOnly);

   auto ldbIter = tx->getIterator();
   for (ldbIter.seekToFirst(); ldbIter.isValid(); ldbIter.advanceAndRead()) {
      auto keyRef = ldbIter.getKeyRef();
      if (keyRef.getSize() != 32) {
         //not a hash entry
         continue;
      }

      auto dataReader = ldbIter.getValueReader();
      std::set<uint64_t> vals;
      for (unsigned i = 0; i < dataReader.getSize() / 8; i++) {
         vals.emplace(dataReader.get_uint64_t());
      }
      hashMap_.emplace(Hash32{keyRef}, std::move(vals));
   }
}

void ScannerContext::merge(ScannerContext& incoming)
{
   //we only care to merge the hashMap from the incoming context
   //we also expect the incoming hashMap has a single txkey per hash
   //therefor, we can use update(hashMap) as is and ignore the return map
   update(incoming.hashMap_);
}

////////
HashMap ScannerContext::update(HashMap& incomingMap)
{
   /*
   We need to insert the known hashes found during the txout scan with
   the context's globla hash map.
   We also need to return the the of inserted hashes, so that they can
   be commited to the db.

   Since this data is updated by the output control thread and read
   by the input parser threads, we want to lock a mutex when updating
   the map and when grabbing it, to reflect changes across all reader
   threads.

   A known hash is a 32 bytes tx hash with it's associated txKey.
   Because of reorgs, the context map may carry multiple txKey for a
   given tx hash (if the tx appears in 2 different branches).
   The map generated by a txout scan always comes with a single key per
   tx hash.
   */
   std::unique_lock<std::mutex> lock(mu_);

   auto hashIter = incomingMap.begin();
   while (hashIter != incomingMap.end()) {
      //try to emplace the <hash, txKey> pair right away
      auto emplaceIter = hashMap_.emplace(
         hashIter->first, hashIter->second);

      if (emplaceIter.second == false) {
         //we already know this hash
         auto& txKeySet = emplaceIter.first->second;
         if (!txKeySet.emplace(*(hashIter->second.begin())).second) {
            //we already know this <hash, txKey> pair, clean up the
            //entry from the incoming map
            incomingMap.erase(hashIter++);
            continue;
         } else {
            //this <hash, blockID> pair is new, reflect the set back
            //into the incoming map
            hashIter->second = txKeySet;
         }
      }
      ++hashIter;
   }

   //at the end of this process, the incoming map should represent
   //all the <hash, blockID> pairs newly inserted
   return std::move(incomingMap);
}

const HashMap& ScannerContext::getHashMap() const
{
   //lock the mutex to reflect the map changes in caller thread
   std::unique_lock<std::mutex> lock(mu_);
   return hashMap_;
}

////////
void ScannerContext::update(std::shared_ptr<Blockchain> bc)
{
   headersById_ = bc->headersById();
}

bool ScannerContext::isBlockIDValid(uint32_t blockID) const
{
   if (blockID <= headersById_.size()) {
      return false;
   }
   return headersById_[blockID]->isMainBranch();
}

////////
void ScannerContext::update(ScrAddrFilter* saf)
{
   scrAddrIds_ = std::move(saf->getScrAddrIds());
}

const ScrAddrIdMap& ScannerContext::getScrAddrIdMap() const
{
   return scrAddrIds_;
}

////////////////////////////////////////////////////////////////////////////////
// ParserBatch
ParserBatch::ParserBatch(unsigned start, unsigned end,
   unsigned startID, unsigned endID, ScannerContext& ctx) :
   start(start), end(end),
   startBlockFileID(startID), targetBlockFileID(endID),
   context(ctx)
{
   if (end < start) {
      throw std::runtime_error("end > start");
   }
   blockCounter.store(start, std::memory_order_relaxed);
}

void ParserBatch::mergeResult(TxOutParsingResult& result)
{
   std::unique_lock<std::mutex> lock(mergeMutex);

   //hash map
   for (auto& hashPair : result.hashMap) {
      outParserResult.hashMap.emplace(std::move(hashPair));
   }

   //txouts
   for (auto& keyPair : result.txOutMap) {
      auto iter = outParserResult.txOutMap.find(keyPair.first);
      if (iter == outParserResult.txOutMap.end()) {
         outParserResult.txOutMap.emplace(std::move(keyPair));
      } else {
         auto& thisMap = iter->second;
         for (auto& blockIdPair : keyPair.second) {
            thisMap.emplace(std::move(blockIdPair));
         }
      }
   }

   //block data
   for (auto blockPair : result.blockMap) {
      outParserResult.blockMap.emplace(blockPair);
   }
}

void ParserBatch::mergeResult(TxInParsingResult& result)
{
   std::unique_lock<std::mutex> lock(mergeMutex);

   //txins
   for (auto& keyPair : result.txInMap) {
      inParserResult.txInMap.emplace(std::move(keyPair));
   }
}

////////////////////////////////////////////////////////////////////////////////
// BlockchainScanner
BlockchainScanner::BlockchainScanner(
   std::shared_ptr<Blockchain> bc, LMDBBlockDatabase* db,
   ScrAddrFilter* saf,
   std::shared_ptr<BlockFiles> bf,
   unsigned threadcount, unsigned queue_depth,
   ProgressCallback prg, bool reportProgress) :
   blockchain_(bc), db_(db), scrAddrFilter_(saf),
   blockFiles_(bf),
   totalThreadCount_(threadcount), writeQueueDepth_(queue_depth),
   totalBlockFileCount_(bf->fileCount()),
   progress_(prg), reportProgress_(reportProgress)
{
   fatalError_.store(0, std::memory_order_relaxed);
}

////////
bool BlockchainScanner::scan(ScannerContext& ctx, int32_t scanFrom)
{
   if (scanFrom > (int32_t)blockchain_->top()->getBlockHeight()) {
      return true;
   }

   //context prep
   TIMER_RESTART("scan_nocheck");
   ctx.update(scrAddrFilter_);
   ctx.update(blockchain_);

   startAt_ = scanFrom;
   auto topBlock = blockchain_->top();

   //start control threads
   std::thread commit_tID([this](){ commitBatches(); });
   std::thread outputs_tID([this](){ processOutputs(); });
   std::thread inputs_tID([this](){ processInputs(); });

   auto startHeight = scanFrom;
   unsigned endHeight = 0;

   std::vector<std::future<bool>> completedFutures;
   unsigned batchCount = 0;
   completedBatches_.store(0, std::memory_order_relaxed);

   //loop until there are no more blocks available
   try {
      unsigned firstBlockFileID = UINT32_MAX;
      unsigned targetBlockFileID = UINT32_MAX;

      while (startHeight <= (int32_t)topBlock->getBlockHeight()) {
         //figure out how many blocks to pull for this batch
         //batches try to grab up nBlockFilesPerBatch_ worth of block data
         unsigned targetHeight = 0;
         size_t targetSize = BATCH_SIZE;
         size_t tallySize;
         try {
            std::shared_ptr<BlockHeader> currentHeader =
               blockchain_->getHeaderByHeight(startHeight);
            firstBlockFileID = currentHeader->getBlockFileNum();

            targetBlockFileID = 0;
            targetHeight = startHeight;
            tallySize = currentHeader->getBlockSize();

            while (tallySize < targetSize) {
               currentHeader = blockchain_->getHeaderByHeight(++targetHeight);
               tallySize += currentHeader->getBlockSize();

               if (currentHeader->getBlockFileNum() < firstBlockFileID) {
                  firstBlockFileID = currentHeader->getBlockFileNum();
               }
               if (currentHeader->getBlockFileNum() > targetBlockFileID) {
                  targetBlockFileID = currentHeader->getBlockFileNum();
               }
            }
         } catch (const std::range_error& e) {
            //if getHeaderByHeight throws before targetHeight is topBlock's height,
            //something went wrong. Otherwise we just hit the end of the chain.

            if (targetHeight < topBlock->getBlockHeight()) {
               LOGERR << e.what();
               return false;
            } else {
               targetHeight = topBlock->getBlockHeight();
               if (targetBlockFileID < topBlock->getBlockFileNum()) {
                  targetBlockFileID = topBlock->getBlockFileNum();
               }
            }
         }
         endHeight = targetHeight;

         //create batch
         auto batch = std::make_unique<ParserBatch>(
            startHeight, endHeight,
            firstBlockFileID, targetBlockFileID,
            ctx);
         completedFutures.push_back(batch->completedPromise.get_future());
         batch->count = batchCount;

         //post for txout parsing
         outputQueue_.push_back(move(batch));
         if (batchCount - completedBatches_.load(std::memory_order_relaxed) >=
            writeQueueDepth_) {
            try {
               auto futIter = completedFutures.begin() +
                  (batchCount - writeQueueDepth_);
               futIter->wait();
            } catch (const std::future_error &e) {
               LOGERR << "future error";
               return false;
            }
         }

         ++batchCount;
         startHeight = endHeight + 1;
      }
   } catch (const std::range_error&) {
      LOGERR << "failed to grab block data starting height: " << startHeight;
      if (startHeight == scanFrom) {
         LOGERR << "no block data was scanned";
      }
   } catch (...) {
      LOGWARN << "scanning halted unexpectedly";
      //let the scan terminate
   }

   //mark all queues complete
   outputQueue_.completed();

   if (outputs_tID.joinable()) {
      outputs_tID.join();
   }
   if (inputs_tID.joinable()) {
      inputs_tID.join();
   }
   if (commit_tID.joinable()) {
      commit_tID.join();
   }

   TIMER_STOP("scan_nocheck");
   if (topBlock->getBlockHeight() - scanFrom > 100) {
      auto timeSpent = TIMER_READ_SEC("scan_nocheck");
      LOGINFO << "scanned transaction history in " << timeSpent << "s";
   }

   auto timeSpent = TIMER_READ_SEC("throttling");
   if (timeSpent > 5) {
      LOGINFO << "throttling for " << timeSpent << "s";
   }
   return fatalError_.load(std::memory_order_relaxed) == 0;
}

////////
void BlockchainScanner::processOutputs()
{
   TIMER_RESET("throttling");
   TIMER_RESET("preload");
   TIMER_RESET("outputs");

   auto process_thread = [this](ParserBatch* batch)->void
   {
      this->processOutputsThread(batch);
   };

   std::map<unsigned, std::shared_ptr<FileUtils::FileCopy>> localFileCopies;
   auto preloadBlockDataFiles = [&](ParserBatch* batch)->void
   {
      if (batch == nullptr) {
         return;
      }

      TIMER_START("preload");

      auto fileId = batch->startBlockFileID;
      while (fileId <= batch->targetBlockFileID) {
         auto fileIter = localFileCopies.find(fileId);
         if (fileIter != localFileCopies.end()) {
            batch->fileCopies.emplace(fileId, fileIter->second);
         } else {
            auto filePath = blockFiles_->getFilePathForID(fileId);
            auto fileCopy = std::make_shared<FileUtils::FileCopy>(filePath);
            if (Config::DBSettings::isXored()) {
               fileCopy->xorMe(Config::DBSettings::getXorKey());
            }
            batch->fileCopies.emplace(fileId, fileCopy);
         }
         ++fileId;
      }
      localFileCopies = batch->fileCopies;

      TIMER_STOP("preload");
   };

   //init batch
   std::unique_ptr<ParserBatch> batch;
   while (true) {
      try {
         batch = std::move(outputQueue_.pop_front());
         break;
      } catch (const Threading::StopBlockingLoop&) {}
   }

   preloadBlockDataFiles(batch.get());
   while (true) {
      //start processing threads
      std::vector<std::thread> thr_vec;
      thr_vec.reserve(totalThreadCount_);
      for (unsigned i = 0; i < totalThreadCount_; i++) {
         thr_vec.emplace_back(std::thread(process_thread, batch.get()));
      }

      TIMER_START("throttling");
      std::unique_ptr<ParserBatch> nextBatch;
      try {
         nextBatch = std::move(outputQueue_.pop_front());
      } catch (const Threading::StopBlockingLoop&) {}
      TIMER_STOP("throttling");

      //populate the next batch's file map while the first
      //batch is being processed
      TIMER_START("outputs");
      preloadBlockDataFiles(nextBatch.get());

      //wait on threads
      for (auto& thr : thr_vec) {
         if (thr.joinable()) {
            thr.join();
         }
      }

      //push first batch for input processing
      inputQueue_.push_back(std::move(batch));

      //check loop break condition
      if (nextBatch == nullptr || fatalError_.load(std::memory_order_relaxed) != 0) {
         TIMER_STOP("outputs");
         break;
      }

      //set batch for next iteration
      batch = std::move(nextBatch);

      TIMER_STOP("outputs");
   }

   //done with processing ouputs, there won't be anymore batches to push
   //to the input queue, we can mark it complete
   inputQueue_.completed();
}

void BlockchainScanner::processInputs()
{
   TIMER_RESET("inputs");

   auto process_thread = [this](ParserBatch* batch)->void
   {
      this->processInputsThread(batch);
   };

   while (true) {
      std::unique_ptr<ParserBatch> batch;
      try {
         batch = std::move(inputQueue_.pop_front());
      } catch (const Threading::StopBlockingLoop&) {
         //end condition
         break;
      }

      if (fatalError_.load(std::memory_order_relaxed) != 0) {
         //fatal error in the batch, stop whole scan
         commitQueue_.completed();
         return;
      }

      //reset counter
      TIMER_START("inputs");
      batch->blockCounter.store(batch->start, std::memory_order_relaxed);

      //merge utxo map from batch with global one
      //this data needs copied because we still have use for the original map
      batch->inParserResult.diff =
         batch->context.update(batch->outParserResult.hashMap);

      //start processing threads
      std::vector<std::thread> thr_vec;
      for (unsigned i = 1; i < totalThreadCount_; i++) {
         thr_vec.emplace_back(std::thread(process_thread, batch.get()));
      }
      process_thread(batch.get());

      //wait on threads
      for (auto& thr : thr_vec) {
         if (thr.joinable()) {
            thr.join();
         }
      }

      //push for commit
      commitQueue_.push_back(std::move(batch));
      TIMER_STOP("inputs");
   }

   //done with processing inputs, there won't be anymore batches to push
   //to the commit queue, we can mark it complete
   commitQueue_.completed();
}

////////
std::shared_ptr<BlockData> BlockchainScanner::getBlockData(
   ParserBatch* batch, unsigned height)
{
   //grab block file map
   auto blockheader = blockchain_->getHeaderByHeight(height);
   auto filenum = blockheader->getBlockFileNum();
   auto mapIter = batch->fileCopies.find(filenum);
   if (mapIter == batch->fileCopies.end()) {
      LOGERR << "Missing file map for output scan, this is unexpected";
      LOGERR << "Has the following block files:";
      for (const auto& file_pair : batch->fileCopies) {
         LOGERR << " --- #" << file_pair.first;
      }
      LOGERR << "Was looking for id #" << filenum;
      throw std::runtime_error("missing file map");
   }

   auto filemap = mapIter->second.get();
   if (!filemap->isValid()) {
      LOGERR << "Invalid FileMap for height " << height;
      throw std::runtime_error("Invalid FileMap");
   }

   try {
      auto bdata = BlockData::deserialize(
         filemap->ptr() + blockheader->getOffset(),
         blockheader->getBlockSize(),
         blockheader, BlockData::CheckHashes::NoChecks);
      return bdata;
   } catch (const std::exception&) {
      blockchain_->flagBlockHeader(blockheader, db_);
      return nullptr;
   }
}

////////
void BlockchainScanner::processOutputsThread(ParserBatch* batch)
{
   TxOutParsingResult result;

   auto scrAddrIdMap = batch->context.getScrAddrIdMap();
   while (true) {
      //shutdown all output workers if the batch encountered a fatal error
      if (fatalError_.load(std::memory_order_relaxed) != 0) {
         return;
      }

      auto currentBlock = batch->blockCounter.fetch_add(
         1, std::memory_order_relaxed);
      if (currentBlock > batch->end) {
         break;
      }

      auto blockdata = getBlockData(batch, currentBlock);
      if (blockdata == nullptr) {
         LOGERR << "Could not get block data for height #" << currentBlock;
         fatalError_.store(1, std::memory_order_relaxed);
         return;
      }
      result.blockMap.emplace(currentBlock, blockdata);

      const auto header = blockdata->getHeaderPtr();
      const auto& txns = blockdata->getTxns();
      for (uint16_t i = 0; i < txns.size(); i++) {
         const BCTX& txn = *(txns[i].get());
         for (uint16_t y = 0; y < txn.txouts_.size(); y++) {
            const auto& txout = txn.txouts_[y];

            BinaryRefReader brr{txn.data_ + txout.first, txout.second};
            brr.advance(8);
            unsigned scriptSize = (unsigned)brr.get_var_int();
            auto scrAddr = BtcUtils::getTxOutScrAddr(
               brr.get_BinaryDataRef(scriptSize));

            auto saIter = scrAddrIdMap.find(scrAddr);
            if (saIter == scrAddrIdMap.end()) {
               continue;
            }
            /* if we got this far, this txout is ours */

            //track known hash and its txkey
            auto txKey = DBUtils::constructTxKey(header->getUniqueID(), i);
            const auto& txHash = txn.getHash();
            result.hashMap.emplace(txHash, std::set<uint64_t>{txKey});

            //track txout data via scrAddr unique id
            const auto& scrAddrUniqueId = saIter->second;
            auto txOutIter = result.txOutMap.find(scrAddrUniqueId);
            if (txOutIter == result.txOutMap.end()) {
               txOutIter = result.txOutMap.emplace(scrAddrUniqueId,
                  std::map<uint32_t, std::deque<TxOutData>>{}).first;
            }

            //get tx out value from script
            brr.resetPosition();
            uint64_t value = brr.get_uint64_t();

            //append to txout deque
            auto emplaceResult = txOutIter->second.emplace(
               header->getUniqueID(), std::deque<TxOutData>{}).first;
            emplaceResult->second.emplace_back(TxOutData{
               value, header->getUniqueID(), i, y});
         }
      }
   }

   //merge thread result to batch result
   batch->mergeResult(result);
}

void BlockchainScanner::processInputsThread(ParserBatch* batch)
{
   TxInParsingResult result;

   const auto& hashMap = batch->context.getHashMap();
   while (true) {
      //shutdown all input workers if the batch encountered a fatal error
      if (fatalError_.load(std::memory_order_relaxed) != 0) {
         return;
      }

      auto currentBlock = batch->blockCounter.fetch_add(
         1, std::memory_order_relaxed);

      if (currentBlock > batch->end) {
         break;
      }

      auto blockDataIter = batch->outParserResult.blockMap.find(currentBlock);
      if (blockDataIter == batch->outParserResult.blockMap.end()) {
         LOGERR << "can't find block #" << currentBlock << " in batch";
         fatalError_.store(1, std::memory_order_relaxed);
         return;
      }

      auto blockdata = blockDataIter->second;
      const auto header = blockdata->getHeaderPtr();
      const auto& txns = blockdata->getTxns();

      for (unsigned i = 0; i < txns.size(); i++) {
         const BCTX& txn = *(txns[i].get());

         for (unsigned y = 0; y < txn.txins_.size(); y++) {
            const auto& txin = txn.txins_[y];
            BinaryDataRef outHash(txn.data_ + txin.first, 32);
            auto hashIter = hashMap.find(outHash);
            if (hashIter == hashMap.end()) {
               continue;
            }

            /*
            We know this tx hash. Track the input.

            Optimization trick: we track all inputs that consume a known
            hash, regardless of txOut index matching.

            This txIn may or may not affect our known scrAddr, but since
            we do not tie txIns to scrAddr, only txOuts, we do not need to
            know.

            This cuts on a lot of complexity for context bootstrap:
             - it's easy to know which txhash affects us
             - it's hard to know which outputs within the tx affect us

            The extra data is negligible.
            */
            uint64_t txKey = *(hashIter->second.begin());
            if (hashIter->second.size() != 1) {
               //multiple blocks carry this hash, grab the valid one
               txKey = UINT64_MAX;
               for (const auto& key : hashIter->second) {
                  auto blockID = DBUtils::getBlockIDFromScrAddrKey(key);
                  if (batch->context.isBlockIDValid(blockID)) {
                     txKey = key;
                     break;
                  }
               }
               if (txKey == UINT64_MAX) {
                  //this should never happen
                  throw std::runtime_error(
                     "could not find a valid block for this hash!");
               }
            }

            //create keys, add to result map
            uint32_t outpointId;
            memcpy(&outpointId, txn.data_ + txin.first + 32, 4);
            uint64_t txOutKey = DBUtils::constructTxIOKeyFromTxKey(txKey, (uint16_t)outpointId);
            uint64_t txInKey = DBUtils::constructTxIOKey(header->getUniqueID(), i, y);
            result.txInMap.emplace(txOutKey, txInKey);
         }
      }
   }

   //merge process data into batch
   batch->mergeResult(result);
}

////////
void BlockchainScanner::commitBatches()
{
   auto getGlobalOffsetForBlock = [bc=blockchain_](unsigned height)->size_t
   {
      auto header = bc->getHeaderByHeight(height);
      size_t val = header->getBlockFileNum();
      val *= 128 * 1024 * 1024;
      val += header->getOffset();
      return val;
   };

   ProgressCalculator calc(getGlobalOffsetForBlock(
      blockchain_->top()->getBlockHeight()));
   auto initVal = getGlobalOffsetForBlock(startAt_);
   calc.init(initVal);
   if (reportProgress_) {
      progress_(BDMPhase_Rescan,
      calc.fractionCompleted(), UINT32_MAX,
      initVal);
   }

   TIMER_RESET("write");

   while (true) {
      std::unique_ptr<ParserBatch> batch;
      try {
         batch = std::move(commitQueue_.pop_front());
      } catch (const Threading::StopBlockingLoop&) {
         break;
      }

      TIMER_START("write");

      //sanity check
      auto& outData = batch->outParserResult;
      if (outData.blockMap.empty()) {
         continue;
      }

      /* serialize the data */

      auto topheader = outData.blockMap.rbegin()->second->getHeaderPtr();
      if (topheader == nullptr) {
         LOGERR << "empty top block header ptr, aborting scan";
         throw std::runtime_error("nullptr header");
      }

      //txouts
      std::map<uint64_t, BinaryWriter> serializedTxOuts;
      for (const auto& txoutPair : outData.txOutMap) {
         uint64_t scrAddrKey64 = (uint64_t)txoutPair.first;

         for (const auto& blockIdPair : txoutPair.second) {
            auto saKey = scrAddrKey64 | (uint64_t)htonl(blockIdPair.first) << 32;
            auto emplaceIter = serializedTxOuts.emplace(
               saKey, BinaryWriter{12 * blockIdPair.second.size()}).first;
            auto& bw = emplaceIter->second;
            for (const auto& txout : blockIdPair.second) {
               bw.put_uint64_t(txout.amount);
               bw.put_uint16_t(txout.txId);
               bw.put_uint16_t(txout.txOutId);
            }
         }
      }

      //txins are serialized in place at creation time
      auto& inData = batch->inParserResult;
      auto serializedTxIns = std::move(inData.txInMap);

      //known hashes
      std::map<Hash32, BinaryWriter> serializedHashes;
      for (auto& hashPair : inData.diff) {
         auto iter = serializedHashes.emplace(std::move(hashPair.first),
            BinaryWriter{hashPair.second.size() * sizeof(uint64_t)}).first;
         auto& bw = iter->second;
         for (const auto& key : hashPair.second) {
            bw.put_uint64_t(key);
         }
      }

      /* write the data */

      //txouts
      {
         auto tx = db_->beginTransaction(
            DB_SELECT::TXOUTS, LMDB::Mode::ReadWrite);
         for (const auto& txoPair : serializedTxOuts) {
            LMDB::DataRef keyRef{sizeof(uint64_t), (const uint8_t*)&txoPair.first};
            auto valBdr = txoPair.second.getDataRef();
            LMDB::DataRef valRef{valBdr.getSize(), valBdr.getPtr()};
            tx->insert(keyRef, valRef);
         }
      }

      //txins
      {
         auto tx = db_->beginTransaction(
            DB_SELECT::TXINS, LMDB::Mode::ReadWrite);
         for (const auto& txiPair : serializedTxIns) {
            LMDB::DataRef keyRef{sizeof(uint64_t), (const uint8_t*)&txiPair.first};
            LMDB::DataRef valRef{sizeof(uint64_t), (const uint8_t*)&txiPair.second};
            tx->insert(keyRef, valRef);
         }
      }

      //known hashes
      {
         auto tx = db_->beginTransaction(
            DB_SELECT::KNOWNHASHES, LMDB::Mode::ReadWrite);
         for (const auto& khPair : serializedHashes) {
            LMDB::DataRef keyRef{32, (const uint8_t*)khPair.first.data};
            auto valBdr = khPair.second.getDataRef();
            LMDB::DataRef valRef{valBdr.getSize(), valBdr.getPtr()};
            tx->insert(keyRef, valRef);
         }
      }

      if (batch->start != batch->end) {
         LOGINFO << "scanned from block #" << batch->start
            << " to #" << batch->end;
      } else {
         LOGINFO << "scanned block #" << batch->start;
      }

      size_t progVal = getGlobalOffsetForBlock(batch->end);
      calc.advance(progVal);
      if (reportProgress_) {
         progress_(BDMPhase_Rescan,
         calc.fractionCompleted(), calc.remainingSeconds(),
         progVal);
      }
      topScannedBlockHash_ = topheader->getThisHash();

      completedBatches_.fetch_add(1, std::memory_order_relaxed);
      batch->completedPromise.set_value(true);

      TIMER_STOP("write");
   }
}

////////
#if 0
void BlockchainScanner::processAndCommitTxHints(ParserBatch* batch)
{
   map<BinaryData, StoredTxHints> txHints;
   map<BinaryData, BinaryWriter> countAndHash;

   auto addTxHint = 
      [&](StoredTxHints& stxh, const StoredTxOut& utxo)->void
   {
      auto utxokey = utxo.getDBKeyOfParentTx(false);

      //make sure key isn't already in there
      for (auto& key : stxh.dbKeyList) {
         if (key == utxokey) {
            return;
         }
      }
      stxh.dbKeyList.emplace_back(move(utxokey));
   };

   auto addTxHintMap =
      [&](const pair<BinaryData, map<unsigned, StoredTxOut>>& utxomap)->void
   {
      auto&& txHashPrefix = utxomap.first.getSliceCopy(0, 4);
      StoredTxHints& stxh = txHints[txHashPrefix];

      //pull txHint from DB first, don't want to override 
      //existing hints
      if (!stxh.isInitialized()) {
         db_->getStoredTxHints(stxh, txHashPrefix);
      }
      for (auto& utxo : utxomap.second) {
         addTxHint(stxh, utxo.second);
      }
      stxh.preferredDBKey = stxh.dbKeyList.front();

      //count and hash
      auto& stxo = utxomap.second.begin()->second;
      auto& bw = countAndHash[stxo.getDBKeyOfParentTx(true)];
      if (bw.getSize() != 0) {
         return;
      }
      bw.put_uint32_t(stxo.parentTxOutCount);
      bw.put_BinaryData(utxomap.first);
   };

   {
      auto hintdbtx = db_->beginTransaction(
         DB_SELECT::TXHINTS, LMDB::Mode::ReadOnly);
      for (const auto& utxomap : batch->outputMap_) {
         addTxHintMap(utxomap);
      }

      map<BinaryData, map<unsigned, StoredTxOut>> spentTxOutMap;
      for (auto& stxo : batch->spentOutputs_) {
         auto& stxomap = spentTxOutMap[stxo.spenderHash];
         StoredTxOut spentstxo;
         spentstxo.parentHash = stxo.spenderHash;
         spentstxo.blockHeight =
            DBUtils::hgtxToHeight(stxo.spentByTxInKey.getSliceRef(0, 4));

         spentstxo.txIndex =
            READ_UINT16_BE(stxo.spentByTxInKey.getSliceRef(4, 2));
         spentstxo.txOutIndex =
            READ_UINT16_BE(stxo.spentByTxInKey.getSliceRef(6, 2));

         spentstxo.parentTxOutCount = stxo.parentTxOutCount;
         stxomap.emplace(spentstxo.txOutIndex, move(spentstxo));
      }

      for (auto& stxomap : spentTxOutMap) {
         addTxHintMap(stxomap);
      }
   }

   map<BinaryData, BinaryWriter> serializedHints;

   //serialize
   for (auto& txhint : txHints) {
      auto& bw = serializedHints[txhint.second.getDBKey()];
      txhint.second.serializeDBValue(bw);
   }

   //write
   {
      auto hintdbtx = db_->beginTransaction(
         DB_SELECT::TXHINTS, LMDB::Mode::ReadWrite);

      for (auto& txhint : serializedHints) {
         db_->putValue(DB_SELECT::TXHINTS,
            txhint.first.getRef(),
            txhint.second.getDataRef());
      }

      for (auto& cah : countAndHash) {
         db_->putValue(DB_SELECT::TXHINTS,
            cah.first.getRef(),
            cah.second.getDataRef());
      }
   }
}
#endif

////////
void BlockchainScanner::processFilterHitsThread(
   std::map<uint32_t, std::map<uint32_t, std::set<const TxHashHints*>>>& filtersResultMap,
   const std::set<BinaryData>& missingHashes, std::atomic<int>& counter,
   std::map<BinaryData, BinaryData>& results,
   std::function<void(size_t)>)
{
   std::map<BinaryData, BinaryData> result;
   uint32_t missedBlocks = 0;

   auto resolveHashes =
      [&](uint32_t fileNum,
      std::map<uint32_t, std::set<const TxHashHints*>> filterHit,
      std::set<BinaryData>& hashSet)->void
   {
      auto filePath = blockFiles_->getFilePathForID(fileNum);
      FileUtils::FileMap fileMap(filePath);

      for (auto& blockkey : filterHit) {
         std::shared_ptr<BlockHeader> headerPtr;
         try {
            headerPtr = blockchain_->getHeaderById(blockkey.first);
         } catch (const std::range_error&) {
            //no block for this id, this is an orphan
            missedBlocks++;
            continue;
         }

         //search the block
         std::shared_ptr<BlockData> bdata;
         try {
            bdata = BlockData::deserialize(
               fileMap.ptr() + headerPtr->getOffset(),
               headerPtr->getBlockSize(),
               headerPtr, BlockData::CheckHashes::NoChecks);
         } catch (const BtcUtils::BlockDeserializingException& e) {
            LOGERR << "Block deser error while processing tx filters: ";
            LOGERR << "  " << e.what();
            LOGERR << "Skipping this block";
            continue;
         }

         const auto& txns = bdata->getTxns();
         for (const auto& filterhit : blockkey.second) {
            auto iditer = filterhit->filterHits_.find(blockkey.first);
            if (iditer == filterhit->filterHits_.end()) {
               continue;
            }

            const auto& txids = iditer->second;
            for (auto& txid : txids) {
               if (txid >= txns.size()) {
                  continue;
               }
               const auto& txn = txns[txid];
               const auto& txnHash = txn->getHash();

               auto hashIter = hashSet.begin();
               while (hashIter != hashSet.end()) {
                  if (txnHash == *hashIter) {
                     auto countAndHash = WRITE_UINT32_LE(txids.size());
                     countAndHash.append(txnHash);
                     result[countAndHash] = std::move(
                        DBUtils::getBlkDataKeyNoPrefix(
                        headerPtr->getBlockHeight(),
                        0,
                        txid));

                     hashSet.erase(hashIter++);
                     continue;
                  }
                  ++hashIter;
               }
            }
         }
      }
   };

   auto missingHashesCopy = missingHashes;
   while (true) {
      auto index = counter.fetch_sub(1, std::memory_order_relaxed);
      if (index < 0) {
         break;
      }
      auto filterIter = filtersResultMap.find(index);

      auto& blkHitsMap = filterIter->second;
      auto hitsPairIter = blkHitsMap.begin();
      while (hitsPairIter != blkHitsMap.end()) {
         auto& txFilterSet = hitsPairIter->second;

         auto hitsIter = txFilterSet.begin();
         while (hitsIter != txFilterSet.end()) {
            auto hashIter = missingHashesCopy.find((*hitsIter)->hash_);
            if (hashIter != missingHashesCopy.end()) {
               ++hitsIter;
               continue;
            }
            txFilterSet.erase(hitsIter++);
         }

         if (!txFilterSet.empty()) {
            ++hitsPairIter;
            continue;
         }
         blkHitsMap.erase(hitsPairIter++);
      }

      if (blkHitsMap.empty()) {
         continue;
      }
      resolveHashes(filterIter->first, filterIter->second, missingHashesCopy);
   }

   //merge results
   std::unique_lock<std::mutex> lock(resolverMutex_);
   results.insert(result.begin(), result.end());
}

////////
bool BlockchainScanner::resolveTxHashes()
{
   throw std::runtime_error("[BlockchainScanner::resolveTxHashes] not in use currently");
   #if 0
   /***
   the missing hashes entry will always be empty if the db is not set
   to ARMORY_DB_FULL, no need to check dbType here
   ***/

   TIMER_RESTART("resolveHashes");

   if (reportProgress_) {
      progress_(BDMPhase_SearchHashes, 0, UINT32_MAX, 0);
   }

   std::set<BinaryData> missingHashes;
   try {
      missingHashes = move(scrAddrFilter_->getMissingHashes());
   } catch (const std::runtime_error&) {
      //no missing hashes entry, return
      TIMER_STOP("resolveHashes");
      return true;
   }

   if (missingHashes.empty()) {
      TIMER_STOP("resolveHashes");
      return true;
   }

   std::set<BinaryData> resolvedHashes;
   auto originalMissingSet = missingHashes;

   auto hashIter = missingHashes.begin();
   while (hashIter != missingHashes.end()) {
      auto&& dbkey = db_->getDBKeyForHash(*hashIter);
      if (dbkey.empty()) {
         ++hashIter;
         continue;
      }

      resolvedHashes.insert(*hashIter);
      missingHashes.erase(hashIter++);
   }

   std::map<BinaryData, BlockHashVector> relevantFilters;
   LOGINFO << "resolving " << missingHashes.size() << " txhashes";

   //check filters
   auto fetch = [this](uint32_t fileId)->BinaryDataRef
   {
      return this->db_->getFilterPoolDataRef(fileId);
   };
   auto resultMap = TxFilterPoolReader::scanHashes(totalBlockFileCount_,
      fetch, missingHashes, TxFilterPoolMode::Auto);

   std::set<uint32_t> heights;
   std::map<uint32_t, std::map<uint32_t, std::set<const TxHashHints*>>> resultsByHash;
   unsigned missingIDs = 0;
   for (auto& fileNumPair : resultMap) {
      auto& block_result_pair = resultsByHash[fileNumPair.first];

      for (auto& filterHits : fileNumPair.second) {
         for (auto& filterHit : filterHits.filterHits_) {
            try {
               auto header = blockchain_->getHeaderById(filterHit.first);
               auto height = header->getBlockHeight();

               heights.insert(height);
               block_result_pair[filterHit.first].insert(&filterHits);
            } catch (...) {
               ++missingIDs;
            }
         }
      }
   }

   if (missingIDs > 0) {
      LOGINFO << missingIDs << " missing block IDs";
      return false;
   }

   LOGINFO << heights.size() << " blocks hit by tx filters";

   //process filter hits
   std::atomic<int> counter;
   counter.store(resultMap.size() - 1, std::memory_order_relaxed);
   std::map<BinaryData, BinaryData> resolverResults;
   std::vector<std::thread> resolverThreads;

   auto hashCount = missingHashes.size();
   ProgressCalculator calc(hashCount);
   std::mutex progressMutex;
   uint64_t topCount = hashCount;

   auto resolveProgress = [&](size_t count)->void
   {
      if (!reportProgress_) {
         return;
      }

      std::unique_lock<std::mutex> lock(progressMutex, std::defer_lock);
      if (!lock.try_lock()) {
         return;
      }

      if (count > topCount) {
         return;
      }

      topCount = count;
      auto intprog = hashCount - count;
      calc.advance(intprog);
      this->progress_(BDMPhase_ResolveHashes,
         calc.fractionCompleted(), calc.remainingSeconds(), count);
   };

   auto resolverThr = [&](void)->void
   {
      processFilterHitsThread(resultsByHash, missingHashes,
         counter, resolverResults, resolveProgress);
   };

   if (reportProgress_) {
      progress_(BDMPhase_ResolveHashes, 0, UINT32_MAX, 0);
   }

   for (unsigned i = 1; i < totalThreadCount_; i++) {
      resolverThreads.push_back(std::thread(resolverThr));
   }

   resolverThr();
   for (auto& thr : resolverThreads) {
      if (thr.joinable()) {
         thr.join();
      }
   }

   //write the resolved hashes
   {
      std::map<BinaryData, StoredTxHints> txHints;
      std::map<BinaryData, BinaryWriter> serializedHints;
      std::map<BinaryData, BinaryWriter> countAndHash;

      {
         auto hintTx = db_->beginTransaction(DB_SELECT::TXHINTS, LMDB::Mode::ReadOnly);
         for (auto& result : resolverResults) {
            resolvedHashes.insert(result.first);

            //get hashPrefix
            auto hashPrefix = result.first.getSliceRef(4, 4);
            auto& hintObj = txHints[hashPrefix];

            //pull hint if it's fresh
            if (hintObj.getNumHints() == 0) {
               db_->getStoredTxHints(hintObj, hashPrefix);
            }

            //append new key
            hintObj.dbKeyList.emplace_back(result.second);

            //save hash and count under dbkey
            BinaryData dbkey;
            dbkey.append(WRITE_UINT8_LE((uint8_t)DbPrefix::TXDATA));
            dbkey.append(result.second);

            auto& bw = countAndHash[dbkey];
            bw.put_BinaryData(result.first);
         }
      }

      LOGINFO << "found " << resolverResults.size() << " missing hashes";
      for (auto& hint : txHints) {
         BinaryData hintKey(1 + hint.first.getSize());
         hintKey.getPtr()[0] = (uint8_t)DbPrefix::TXHINTS;
         std::memcpy(
            hintKey.getPtr() + 1,
            hint.first.getPtr(),
            hint.first.getSize()
         );
         auto& bw = serializedHints[hintKey];
         hint.second.serializeDBValue(bw);
      }

      //write it
      {
         auto hintTx = db_->beginTransaction(DB_SELECT::TXHINTS, LMDB::Mode::ReadWrite);
         for (auto& toWrite : serializedHints) {
            db_->putValue(DB_SELECT::TXHINTS,
               toWrite.first.getRef(),
               toWrite.second.getDataRef());
         }

         for (auto& toWrite : countAndHash) {
            db_->putValue(DB_SELECT::TXHINTS,
               toWrite.first.getRef(),
               toWrite.second.getDataRef());
         }
      }
   }

   //clean up missing hashes in db
   missingHashes.clear();
   for (auto& hash : originalMissingSet) {
      auto resolvedIter = resolvedHashes.find(hash);
      if (resolvedIter == resolvedHashes.end()) {
         missingHashes.insert(hash);
      }
   }
   scrAddrFilter_->putMissingHashes(missingHashes);

   TIMER_STOP("resolveHashes");
   auto timeElapsed = TIMER_READ_SEC("resolveHashes");
   LOGINFO << "Resolved missing hashes in " << timeElapsed << "s";

   if (!missingHashes.empty()) {
      return false;
   }
   return true;
   #endif
}

const Hash32& BlockchainScanner::getTopScannedBlockHash() const
{
   return topScannedBlockHash_;
}
