////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  Copyright (C) 2017-2026, goatpig                                          //
//  Distributed under the MIT license                                         //
//  See LICENSE-MIT or https://opensource.org/licenses/MIT                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <map>
#include <Utils/SecureBinaryData.h>
#include "WalletIdTypes.h"

#define CIPHER_BYTE              0xB2

#define PRIVKEY_BYTE             0x82
#define ENCRYPTIONKEY_BYTE       0x83

#define CIPHER_DATA_VERSION      0x00000001
#define ENCRYPTION_KEY_VERSION   0x00000001

//fml typo =(
#define HMAC_KEY_ENCRYPTIONKEYS  "EncyrptionKey"

enum CipherType
{
   CipherType_AES,
   CipherType_Serpent
};

namespace Armory
{
   namespace Passphrase
   {
      class SetNew;
   }

   namespace Wallets
   {
      class AssetWallet;
      class AssetWallet_Single;

      namespace Encryption
      {
         class ClearTextEncryptionKey;
         class ClearTextAssetData;
         class KeyDerivationFunction;

         ///////////////////////////////////////////////////////////////////////
         class CipherException : public std::runtime_error
         {
         public:
            CipherException(const std::string&);
         };

         ////
         class Cipher
         {
            /***
            Carries the cipher type and IV. Not copiable, this is by design
            to avoid IV reuse.

            Also carries identifiers to setup encryption state:
            - kdfId_: to apply the proper kdf on the encryption key
            - encryptionKeyId_: hash of the kdf'd passphrase

            A convenience getCopy method is provided to carry context over to
            a new object. This call will result in a fresh IV for the copy. IVs
            are never copied over, the iv has to be generated by the ctor instead.

            It is best to use this class within a std::unique_ptr
            ***/

         private:
            const CipherType type_;

         protected:
            const KdfId kdfId_;
            const EncryptionKeyId encryptionKeyId_;
            const SecureBinaryData iv_;

         private:
            Cipher(const Cipher&) = delete;
            Cipher& operator=(const Cipher&) = delete;

         public:

            //tors
            Cipher(CipherType, const KdfId&, const EncryptionKeyId&);
            Cipher(CipherType, const KdfId&, const EncryptionKeyId&,
               SecureBinaryData&);
            virtual ~Cipher(void) = 0;

            //locals
            CipherType getType(void) const;
            const KdfId& getKdfId(void) const;
            const EncryptionKeyId& getEncryptionKeyId(void) const;
            const SecureBinaryData& getIV(void) const;
            SecureBinaryData generateIV(void) const;
            unsigned getBlockSize(void) const;

            //virtuals
            virtual BinaryData serialize(void) const = 0;
            virtual std::unique_ptr<Cipher> getCopy(void) const = 0;
            virtual std::unique_ptr<Cipher> getCopy(
               const EncryptionKeyId&) const = 0;
            virtual bool isSame(Cipher* const) const = 0;

            virtual SecureBinaryData encrypt(
               ClearTextEncryptionKey* const,
               const KdfId&, const SecureBinaryData&) const = 0;
            virtual SecureBinaryData encrypt(
               ClearTextEncryptionKey* const,
               const KdfId&, ClearTextEncryptionKey* const) const = 0;

            virtual SecureBinaryData decrypt(const SecureBinaryData&,
               const SecureBinaryData&) const = 0;

            //statics
            static std::unique_ptr<Cipher> deserialize(BinaryRefReader&);
            static unsigned getBlockSize(CipherType);
         };

         ///////////////////////////////////////////////////////////////////////
         class Cipher_AES : public Cipher
         {
         public:
            //tors
            Cipher_AES(const KdfId&, const EncryptionKeyId&);

            Cipher_AES(const KdfId&, const EncryptionKeyId&,
               SecureBinaryData&);

            //virtuals
            BinaryData serialize(void) const override;
            std::unique_ptr<Cipher> getCopy(void) const override;
            std::unique_ptr<Cipher> getCopy(
               const EncryptionKeyId&) const override;
            bool isSame(Cipher* const) const override;

            //encrypt
            SecureBinaryData encrypt(ClearTextEncryptionKey* const,
               const KdfId&, const SecureBinaryData&) const override;
            SecureBinaryData encrypt(ClearTextEncryptionKey* const,
               const KdfId&, ClearTextEncryptionKey* const) const override;

            //decrypt
            SecureBinaryData decrypt(const SecureBinaryData&,
               const SecureBinaryData&) const override;

            //utils
            unsigned getBlockSize(void) const;
         };

         ///////////////////////////////////////////////////////////////////////
         struct CipherData
         {
            /*
            Cipher text and its relevant cipher object
            */

            const SecureBinaryData cipherText;
            std::unique_ptr<Cipher> cipher;

            CipherData(SecureBinaryData&, std::unique_ptr<Cipher>);

            BinaryData serialize(void) const;
            bool isSame(CipherData* const) const;

            static std::unique_ptr<CipherData> deserialize(BinaryRefReader&);
         };

         ///////////////////////////////////////////////////////////////////////
         class EncryptionKey
         {
            /*
            May have multiple cipher data objects
            */
            friend class DecryptedDataContainer;

         protected:
            const Wallets::EncryptionKeyId id_;
            std::map<Wallets::EncryptionKeyId,
               std::unique_ptr<CipherData>> cipherDataMap_;

         private:
            Cipher* getCipherPtrForId(
               const Wallets::EncryptionKeyId&) const;
            bool removeCipherData(const Wallets::EncryptionKeyId&);
            bool addCipherData(std::unique_ptr<CipherData>);

         public:
            EncryptionKey(Wallets::EncryptionKeyId&,
               SecureBinaryData&, std::unique_ptr<Cipher>);
            EncryptionKey(Wallets::EncryptionKeyId&,
               std::map<Wallets::EncryptionKeyId, std::unique_ptr<CipherData>>);

            ////
            bool isSame(EncryptionKey* const) const;
            const Wallets::EncryptionKeyId& getId(void) const
            { return id_; }
            BinaryData serialize(void) const;
            static std::unique_ptr<EncryptionKey> deserialize(
               const BinaryDataRef&);

            /*
            TODO:
               - dedicated decrypt per sub class instead of virtual (
               otherwise the return type is always ClearTextAssetData)
            */
            std::unique_ptr<ClearTextAssetData> decrypt(
               const SecureBinaryData&) const;
         };

         ///////////////////////////////////////////////////////////////////////
         class ClearTextEncryptionKey
         {
            friend class DecryptedDataContainer;
            friend class Cipher_AES;
            friend class Wallets::AssetWallet_Single;
            friend class Wallets::AssetWallet;

         private:
            const SecureBinaryData rawKey_;
            std::map<KdfId, SecureBinaryData> derivedKeys_;

         private:
            EncryptionKeyId computeId(const SecureBinaryData&) const;
            const SecureBinaryData& getData(void) const;
            const SecureBinaryData& getDerivedKey(const KdfId&) const;

         public:
            ClearTextEncryptionKey(SecureBinaryData&);
            ClearTextEncryptionKey(Passphrase::SetNew&);

            void deriveKey(std::shared_ptr<KeyDerivationFunction>);
            EncryptionKeyId getId(const KdfId&) const;

            std::unique_ptr<ClearTextEncryptionKey> copy(void) const;
            bool hasData(void) const;
         };

         ///////////////////////////////////////////////////////////////////////
         class ClearTextAssetData
         {
         private:
            const AssetId id_;
            const SecureBinaryData clearText_;

         public:
            ClearTextAssetData(const AssetId&, SecureBinaryData&);

            bool hasData(void) const;
            const AssetId& getId(void) const;
            const SecureBinaryData& getData(void) const;
         };

         ///////////////////////////////////////////////////////////////////////
         class EncryptedAssetData
         {
            /***
            This class holds the cipher data for an encrypted key. It can
            yield the clear text secret, provided the kdf'ed encryption key.
            It cannot generate the cipher text.

            Use Cipher::encrypt to generate the cipher text first. Pass that
            cipher data at construction time.
            ***/

            friend class DecryptedDataContainer;

         protected:
            const EncryptionKeyId& encryptionKeyId_;
            const std::unique_ptr<CipherData> cipherData_;

         public:
            EncryptedAssetData(std::unique_ptr<CipherData>);

            //virtual
            virtual ~EncryptedAssetData(void) = 0;

            virtual bool isSame(EncryptedAssetData* const) const;
            virtual BinaryData serialize(void) const = 0;
            virtual const AssetId& getAssetId(void) const = 0;

            virtual std::unique_ptr<ClearTextAssetData> decrypt(
               const SecureBinaryData& key) const;

            //local
            const SecureBinaryData& getCipherText(void) const;
            const SecureBinaryData& getIV(void) const;
            const EncryptionKeyId& getEncryptionKeyId(void) const;
            const KdfId& getKdfId(void) const;

            bool hasData(void) const;
            const CipherData* getCipherDataPtr(void) const;
         };

      }; //namespace Encryption
   }; //namespace Wallets
}; //namespace Armory
